# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
    # see: https://github.com/fsharp/FAKE/issues/2325#issuecomment-497126177
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    DOTNET_ROLL_FORWARD: "Major"

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .net core 3.0 (preview)'
  inputs:
    version: '3.0.100-preview7-012821'
- script:
    ./fake.sh build target tests no-clean
  displayName: 'Run tests'
